### ISSUE TITLE
An Idea for CommunityBot

### ISSUE THREAD

**Issue by glaicodes** [UP929312/CommunityBot#1]
Maybe there is a menu that you can select what minions you have and what upgrades they have or maybe partner with cowlection mod that can make you see your chests' value.

**Comment by SevereAneurysm** [comment]
Automated via API?
You can view it on other 3rd party sites. So, it should be automated. I think the main issue is deciding if you actually currently have it or not.

**Comment by UP929312** [comment]
I'd prefer for the user to not have to input a bunch of information that takes ages, such as
"Enter minion 1, enter minion 2" etc.
For the most part, I'm considering adding an automatic "Estimated" number, like if you have hyperions, you'll probably have expensive minions too. I'm not sure the implementation of this algorithm yet.

**Comment by UP929312** [comment]
As for partnering with cowlection, not sure how I can access that data and I'd have to handle 2 copies of the code.
